apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: resttemplateserver-sep
  newName: 210.90.24.172:8080/camit/robot$myrobot/resttemplateserver-sep
  newTag: f8fee2610dcf51a25a441cdce062aecaef62710b
